[package]
name = "aggregator"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.13.1"

# This is required for using Spans, Arrays, and Poseidon

core = ">=2.8.2"


[[target.executable]]
name = "aggregator"
function = "aggregator::main"